name:                advent-of-code-y2021
version:             0.1.0.0
github:              "githubuser/advent-of-code-y2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code-y2021#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -W
  - -Werror

executables:
  01-sonar-sweep:
    main:                Main.hs
    source-dirs:         app/01-sonar-sweep
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  02-dive:
    main:                Main.hs
    source-dirs:         app/02-dive
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - split

  03-binary-diagnostic:
    main:                Main.hs
    source-dirs:         app/03-binary-diagnostic
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  04-giant-squid:
    main:                Main.hs
    source-dirs:         app/04-giant-squid
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - split

  05-hydrothermal-venture:
    main:                Main.hs
    source-dirs:         app/05-hydrothermal-venture
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - split
      - containers

  06-lanternfish:
    main:                Main.hs
    source-dirs:         app/06-lanternfish
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - split
